services:
  - type: web
    name: ppm-aircompressor
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
